### ISSUE TITLE
Website Review & Improvements 

### ISSUE THREAD

**Issue by SikandarJODD** [ieedan/geist-ui-svelte#151]
# Simple Issues   
*I have gone through whole website and configured some improvements*
## 1. SEO Tag on Examples Page
Link : [Example](https://geist-ui-svelte.dev/examples) 
## 2. Not able to see borders in Light mode : 
Light mode : 
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/8d37fe91-bf23-4072-8ad2-bcbdbc55ff5c)
Dark Mode : 
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/2e616e1a-23b8-4aae-88eb-cd52f4e20472)
## 4. Dropdown & Drawers Examples should have Padding 
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/cb672ab7-185c-4533-a2e4-97ba53b4b2a1)
## 5. Size of Small Heading should be large than sub headings, also it should be **bold**
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/105e8d42-baef-4c6d-b760-05d0cf19a02f)

**Comment by ieedan** [comment]
1. Yeah we need to add the title to the examples
2. I can see the borders just fine on my screen
3. How would we handle a `Tag` integration with Twitter API? Different social app tagging?
4. I am trying to keep elements from defining their own padding because in some cases you want to change it yourself generally I start using something like dropdown by doing this 
```svelte
<Dropdown>
   <div class="p-2"></div>
</Dropdown>
```
5. We can look at changing the headings
